INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (1, 'Cecilia', 'Blanes', 'cabezasasdrubal@hotmail.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (2, 'Ximena', 'Luján', 'colomerligia@gmail.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (3, 'Felipa', 'Gutierrez', 'bsobrino@garate-pujol.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (4, 'Jose Angel', 'Garriga', 'taboadapascual@yahoo.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (5, 'Esperanza', 'Pereira', 'jose-franciscorocha@porcel.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (6, 'Régulo', 'Castro', 'maxirodriguez@gmail.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (7, 'Consuela', 'Chamorro', 'curro69@jaume.es');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (8, 'Adoración', 'Fernandez', 'mirandafabian@gmail.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (9, 'Joaquín', 'Ferrándiz', 'nicolauanselmo@torrens.org');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (10, 'Sara', 'Jordán', 'noemi52@herranz.net');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (11, 'Milagros', 'Izaguirre', 'hernan18@yahoo.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (12, 'Manu', 'Cabañas', 'dieguezluis@plana-cano.es');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (13, 'Leonor', 'Ramírez', 'hernan55@gmail.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (14, 'Teodosio', 'Codina', 'luis18@calderon.es');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (15, 'Nidia', 'Alfonso', 'albina96@calleja-cordero.es');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (16, 'Cándido', 'Flor', 'rita76@gmail.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (17, 'Angelita', 'Pulido', 'eligiocordero@yahoo.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (18, 'Curro', 'Julián', 'miguelfatima@yahoo.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (19, 'Paz', 'Seguí', 'navarretemargarita@yahoo.com');
INSERT INTO `programacion`.`clientes` (`Identificador`, `nombre`, `apellidos`, `email`) VALUES (20, 'Curro', 'Linares', 'rosa-mariaizaguirre@gmail.com');


INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (1, 'Inventore sudadera', 'Inventore sudadera de alta calidad para uso casual', 86.95);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (2, 'Recusandae camiseta', 'Recusandae camiseta de alta calidad para uso casual', 49.66);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (3, 'Quibusdam sandalias', 'Quibusdam sandalias de alta calidad para uso casual', 69.99);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (4, 'Id sombrero', 'Id sombrero de alta calidad para uso casual', 87.99);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (5, 'Corporis sandalias', 'Corporis sandalias de alta calidad para uso casual', 90.37);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (6, 'Nobis chaqueta', 'Nobis chaqueta de alta calidad para uso casual', 14.68);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (7, 'Veniam sombrero', 'Veniam sombrero de alta calidad para uso casual', 67.42);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (8, 'Quaerat sudadera', 'Quaerat sudadera de alta calidad para uso casual', 39.30);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (9, 'Pariatur pantalón', 'Pariatur pantalón de alta calidad para uso casual', 94.49);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (10, 'Odit pantalón', 'Odit pantalón de alta calidad para uso casual', 99.82);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (11, 'Distinctio chaqueta', 'Distinctio chaqueta de alta calidad para uso casual', 41.17);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (12, 'Voluptatum sandalias', 'Voluptatum sandalias de alta calidad para uso casual', 40.22);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (13, 'Iusto camiseta', 'Iusto camiseta de alta calidad para uso casual', 63.27);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (14, 'Sapiente sudadera', 'Sapiente sudadera de alta calidad para uso casual', 72.08);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (15, 'Quo zapatos', 'Quo zapatos de alta calidad para uso casual', 96.52);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (16, 'Perspiciatis sudadera', 'Perspiciatis sudadera de alta calidad para uso casual', 70.47);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (17, 'Reiciendis gorra', 'Reiciendis gorra de alta calidad para uso casual', 66.13);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (18, 'Voluptas gorra', 'Voluptas gorra de alta calidad para uso casual', 15.28);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (19, 'Assumenda bufanda', 'Assumenda bufanda de alta calidad para uso casual', 75.46);
INSERT INTO `programacion`.`productos` (`Identificador`, `nombre`, `descripcion`, `precio`) VALUES (20, 'Temporibus sombrero', 'Temporibus sombrero de alta calidad para uso casual', 71.92);

INSERT INTO `programacion`.`categorias` (`Identificador`, `nombre`) VALUES (1, 'Camisetas');
INSERT INTO `programacion`.`categorias` (`Identificador`, `nombre`) VALUES (2, 'Pantalones');
INSERT INTO `programacion`.`categorias` (`Identificador`, `nombre`) VALUES (3, 'Sudaderas');
INSERT INTO `programacion`.`categorias` (`Identificador`, `nombre`) VALUES (4, 'Sombreros');
INSERT INTO `programacion`.`categorias` (`Identificador`, `nombre`) VALUES (5, 'Calzado');
