INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Luis', 'Lopez', 'luis.lopez@example.com', 'Avenida Central 95', '1070', 'Ciudad de México', 'Venezuela');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Lucia', 'Rodriguez', 'lucia.rodriguez@example.com', 'Calle Secundaria 79', '4000', 'Madrid', 'Colombia');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Carlos', 'Rodriguez', 'carlos.rodriguez@example.com', 'Plaza Principal 8', '1070', 'Quito', 'Guatemala');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Carlos', 'Romero', 'carlos.romero@example.com', 'Avenida Central 15', '22000', 'Caracas', 'México');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Carlos', 'Sanchez', 'carlos.sanchez@example.com', 'Plaza Principal 56', '11001', 'Buenos Aires', 'México');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Alberto', 'Gonzalez', 'alberto.gonzalez@example.com', 'Pasaje Los Pinos 14', '1070', 'Ciudad de México', 'Ecuador');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Miguel', 'Romero', 'miguel.romero@example.com', 'Plaza Principal 48', '1070', 'Valencia', 'Argentina');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Juan', 'Ortiz', 'juan.ortiz@example.com', 'Calle Secundaria 49', '10001', 'Santiago', 'Ecuador');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Miguel', 'Perez', 'miguel.perez@example.com', 'Avenida Central 59', '4000', 'Lima', 'Chile');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Juan', 'Rodriguez', 'juan.rodriguez@example.com', 'Calle Mayor 10', '11001', 'Quito', 'Uruguay');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Maria', 'Martinez', 'maria.martinez@example.com', 'Pasaje Los Pinos 7', '22000', 'Montevideo', 'España');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Miguel', 'Gonzalez', 'miguel.gonzalez@example.com', 'Plaza Principal 51', '1070', 'Valencia', 'España');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Carmen', 'Lopez', 'carmen.lopez@example.com', 'Plaza Principal 31', '10001', 'Ciudad de México', 'Chile');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Luis', 'Perez', 'luis.perez@example.com', 'Plaza Principal 29', '830000', 'Montevideo', 'Chile');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Miguel', 'Garcia', 'miguel.garcia@example.com', 'Calle Secundaria 22', '11001', 'Quito', 'España');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Luis', 'Romero', 'luis.romero@example.com', 'Plaza Principal 47', '28001', 'Madrid', 'Venezuela');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Miguel', 'Rubio', 'miguel.rubio@example.com', 'Plaza Principal 100', '1070', 'Madrid', 'Venezuela');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Alberto', 'Rubio', 'alberto.rubio@example.com', 'Plaza Principal 79', '22000', 'Valencia', 'Argentina');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Carmen', 'Martinez', 'carmen.martinez@example.com', 'Calle Secundaria 27', '4000', 'Ciudad de México', 'Ecuador');
INSERT INTO crimson.clientes (nombre, apellidos, email, direccion, cp, poblacion, pais) VALUES ('Lucia', 'Perez', 'lucia.perez@example.com', 'Pasaje Los Pinos 67', '830000', 'Caracas', 'México');

